[package]
name = "untyped-hoas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = { version = "2.4.1" }
pest_derive = { version = "2.4.1" }
clap = "4.0.26"